### ISSUE TITLE
slow ping?

### ISSUE THREAD

**Issue by skydiablo** [clue/php-icmp-react#11]
ping requestet via this lib is ten times slower (~20ms) than normal ping via cli (~2ms)... is this known or can i improve this?

**Comment by clue** [comment]
@skydiablo Thanks for bringing this up!

This is covered in the documentation: https://github.com/clue/php-icmp-react#using-an-existing-event-loop

This should not be an issue if you use the simple factory call with its built-in socket loop implementation: https://github.com/clue/php-icmp-react#simple-factory

In the long run, this may be lifted once #6 is addressed :+1:
